{"uuid": "70dfa161-e6ed-408a-8994-603dfeaba9fd", "children": ["98ae819d-ef67-4dba-9636-13835acbb687"], "befores": [{"name": "xunit_setup_class_fixture_Test_request", "status": "broken", "statusDetails": {"message": "TypeError: 'Response' object is not subscriptable\n", "trace": "  File \"C:\\Users\\bonjour\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\bonjour\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\bonjour\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\bonjour\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\bonjour\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\12\\TestCase\\test_request.py\", line 38, in setup_class\n    print(requestdata[\"ndata\"][\"token\"])\n"}, "start": 1643351351202, "stop": 1643351351482}], "start": 1643351351202, "stop": 1643351351600}